##################################################################################
# Cloudify AWS EC2 built in types and plugins definitions.
##################################################################################

plugins:
  cloudify-aws-plugin:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-aws-plugin/archive/master.zip

node_types:
  cloudify.aws.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      instance:
        default: {}
      ami_image_id: {}
      instance_type: {}
      use_external_resource:
        default: false
      resource_id:
        default: ''
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: cloudify-aws-plugin.ec2.instance.run
          inputs: {}
        start:
          implementation: cloudify-aws-plugin.ec2.instance.start
          inputs: {}
        stop:
          implementation: cloudify-aws-plugin.ec2.instance.stop
          inputs: {}
        delete:
          implementation: cloudify-aws-plugin.ec2.instance.terminate
          inputs: {}
      cloudify.interfaces.validation:
        creation:
          implementation: cloudify-aws-plugin.ec2.instance.creation_validation
          inputs: {}